### PR TITLE
django-memcached and Django 1.3

### PR DESCRIPTION
**Pull request by edavis**
I've added the ability for django-memcached to work with the CACHES setting introduced in Django 1.3.

### CODE REVIEW

**Comment by lemieux** [comment]
This would be useful in the pip version. Tested and working.

**Comment by jlipps** [comment]
ditto on the pip version request.

**Comment by ogirardot** [comment]
+1 on the pip version too :)

**Comment by edavis** [comment]
I've pinged @ericflo to see if he has any interest in pulling this in.  If he doesn't, I'll go ahead and cut a release and host it on PyPI as `django-memcached2` or something.

**Comment by dragoon** [comment]
+1 I'm also interested in this update

**Comment by edavis** [comment]
Alright, [django-memcached2](http://pypi.python.org/pypi/django-memcached2) is now available on PyPI.

If you run into any trouble with it, please feel free to [file a ticket](https://github.com/edavis/django-memcached/issues).

**Pull request closed without merging**
